### ISSUE TITLE
showing Normal datetimes insteadof formatted dates

### ISSUE THREAD

**Issue by kiransunkari** [arajajyothibabu/retention-graph-cohort-analysis#1]
Dude  , iam  getting issues when i use your retention graph it is showing  Normal datetime as a field  date - format is not working   and  it is showing unknown 0 , unknown1 instead of day0 ,day1

**Comment by arajajyothibabu** [comment]
Thanks for raising the first issue. Here is the fix for your date format.
I updated the input options with proper date format options

https://github.com/arajajyothibabu/retention-graph-Cohort-analysis/commit/75201dba27ba63a569b3f1a43f125508204d4962****

**Comment by arajajyothibabu** [comment]
Unknown0, unknown1, : day count filter fixed

https://github.com/arajajyothibabu/retention-graph-Cohort-analysis/commit/97c97333afd8bb535b9edbb98020ceff3c32d003
