### ISSUE TITLE
redirection in td

### ISSUE THREAD

**Issue by sirisha-pitta** [arajajyothibabu/retention-graph-cohort-analysis#2]
hello Mr jyothi i  need clickable on td which is need to redirect to another location

**Comment by arajajyothibabu** [comment]
Sure mam, here is the updated input options with `cellClickEvent :` a closure with date and index of day as inputs

https://github.com/arajajyothibabu/retention-graph-Cohort-analysis/commit/78d718af79c47ce4ee21749a08d04f70a606230b
