### ISSUE TITLE
Restrict start and enddates to a week

### ISSUE THREAD

**Issue by itssunilsid** [arajajyothibabu/retention-graph-cohort-analysis#3]
plugin size is excellent but putting query in a week interval gives an non-scrollable view which looks awesome.

**Comment by arajajyothibabu** [comment]
Restricting date range is not a good practice. But somehow managed to give dateRange option through
`enableDateRange : true`
[Here](https://github.com/arajajyothibabu/retention-graph-Cohort-analysis/commit/b6c0a6e387ff49c8f27ae47076db67cea0bfeb5b) is the diff
