### ISSUE TITLE
if value is not present it is giving Nan%

### ISSUE THREAD

**Issue by kiransunkari** [arajajyothibabu/retention-graph-cohort-analysis#4]
if in my json object there is no values for the day it is showing Nan% instead it has to show 0%, please fix this issue .

**Comment by arajajyothibabu** [comment]
Thanks for finding the bug. It's a big issue
[Here](https://github.com/arajajyothibabu/retention-graph-Cohort-analysis/commit/b9024bc208fe67aa26570c477e31ff3f3e5adfd7) is the fix
