### ISSUE TITLE
Error in column percentage calculation

### ISSUE THREAD

**Issue by ijsuhit** [arajajyothibabu/retention-graph-cohort-analysis#5]
In the cohort, if on Jan 1st, 100 users visited for the first time and till Jan 8th there are 100 new users each day, then total there are 800 new users. The Day 7 calculation should be only based on Jan 1st, (because it says "out of all users who came on Jan 1st (100 in this case), how many visited on Day 7?) 
So, if that number is 50, then the % is 50%.

This number is correctly shown in the cell. But on the column header (where Day 7 is written) that % is calculated based on the whole 800 users, which is absurd. This should be corrected.

**Comment by arajajyothibabu** [comment]
Thank you @ijsuhit You must awarded with a cup of coffee. 
Here is the [fix](https://github.com/arajajyothibabu/retention-graph-Cohort-analysis/commit/2432d80e6f1e734d9ca3e05f568d7f0ae0858b9a )
